//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleRegExExample.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleRegExExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///    
        ///&lt;html&gt; &lt;head&gt;
        ///  &lt;script&gt;
        /// (function(w, d, s, l, i) {
        /// w[l] = w[l] || [];
        /// w[l].push({
        /// &apos;gtm.start&apos;: new Date().getTime(),
        /// event: &apos;gtm.js&apos;
        /// });
        /// var f = d.getElementsByTagName(s)[0],
        /// j = d.createElement(s),
        /// dl = l != &apos;dataLayer&apos; ? &apos;&amp;l=&apos; + l : &apos;&apos;;
        /// j.async = true;
        /// j.src = &apos;//www.googletagmanager.com/gtm.js?id=&apos; + i + dl;
        /// f.parentNode.insertBefore(j, f);
        /// })(window, document, &apos;script&apos;, &apos;dataLayer&apos;, &apos;GTM-KP9Q9H&apos;);
        /// &lt;/script&gt;
        /// &lt;meta charset=&quot;utf-8&quot;&gt;
        ///   &lt;meta name=&quot;for [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///    
        ///&lt;html&gt; &lt;head&gt;
        ///  &lt;script&gt;
        /// (function(w, d, s, l, i) {
        /// w[l] = w[l] || [];
        /// w[l].push({
        /// &apos;gtm.start&apos;: new Date().getTime(),
        /// event: &apos;gtm.js&apos;
        /// });
        /// var f = d.getElementsByTagName(s)[0],
        /// j = d.createElement(s),
        /// dl = l != &apos;dataLayer&apos; ? &apos;&amp;l=&apos; + l : &apos;&apos;;
        /// j.async = true;
        /// j.src = &apos;//www.googletagmanager.com/gtm.js?id=&apos; + i + dl;
        /// f.parentNode.insertBefore(j, f);
        /// })(window, document, &apos;script&apos;, &apos;dataLayer&apos;, &apos;GTM-KP9Q9H&apos;);
        /// &lt;/script&gt;
        /// &lt;meta charset=&quot;utf-8&quot;&gt;
        ///   &lt;meta name=&quot;for [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string html2 {
            get {
                return ResourceManager.GetString("html2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;item item_list.*id=&quot;(.*?)&quot;.*type=&quot;(.*?)&quot;[\s,\S,\n]*?&lt;div class=&quot;price&quot;&gt;.*?&lt;p&gt;([\s,\S,\n]*?)&lt;/p&gt;[\s,\S,\n]*?photo\&quot;&gt;([\s,\S,\n]*?)&lt;/div&gt;[\s,\S,\n]*?class=&quot;data[\s,\S,\n]*?&gt;([\s,\S,\n]*?)&lt;/div&gt;[\s,\S,\n]*?id=\&quot;(.*?)\&quot;.*?href=\&quot;(.*?)\&quot;.*?title=\&quot;(.*?)\&quot;&gt;(.*?)&lt;/a&gt;[\s,\S,\n]*?&lt;span class=&quot;date&quot;&gt;([\s,\S,\n]*?)&lt;/span&gt;[\s,\S,\n]*?[\s,\S,\n]*?(.*?)&lt;/div&gt;.
        /// </summary>
        internal static string Regex1 {
            get {
                return ResourceManager.GetString("Regex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;title-info-metadata-item[\s,\S,\n]*?}&apos;&gt;([\s,\S,\n]*?)\(([\s,\S,\n]*?)\)[\s,\S,\n]*?&lt;/a&gt;[\s,\S,\n]*?&lt;div class=&quot;item-description&quot;&gt;[\s,\S,\n]*?&lt;p&gt;([\s,\S,\n]*?)&lt;/div&gt;.
        /// </summary>
        internal static string Regex2 {
            get {
                return ResourceManager.GetString("Regex2", resourceCulture);
            }
        }
    }
}
